// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sbfpdjapcxlsnqkpgsas.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNiZnBkamFwY3hsc25xa3Bnc2FzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MTM3NjcsImV4cCI6MjA3MDA4OTc2N30.fsRwSKW3tbyyhsLuBkjitK2CK3F7sIM5Uee06B6bOKw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});